// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using calculodeequipamentos.Context;

#nullable disable

namespace calculodeequipamentos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("calculodeequipamentos.Models.EquipamentoEletronico", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Consumo")
                        .HasColumnType("float");

                    b.Property<int>("Potencia")
                        .HasColumnType("int");

                    b.Property<int>("TempoDeUso")
                        .HasColumnType("int");

                    b.HasKey("Nome");

                    b.ToTable("Equipamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
